services:
  postgres:
    image: postgres:latest
    env_file:
      - .env.local
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    env_file:
      - .env.local
    environment:
      ADMINER_DEFAULT_SERVER: postgres

volumes:
  postgres_data:
